### ISSUE TITLE
Normal formatting

### ISSUE THREAD

**Issue by ioquatix** [dominikh/filesize#12]
I feel like there should not be a space between the number and the unit. For example, the output of `du`.

**Comment by dominikh** [comment]
We're following SI here, which dictates a (small) space. If a small space isn't available, the next best substitution is a full space. 

> There is a space between the numerical value and unit symbol, even when the value is used in an adjectival sense, except in the case of superscript units for plane angle. 

If you disagree with SI/the defaults of this gem, there are various ways of removing the space/constructing desired output yourself. But the default behaviour will not be changed.

**Comment by ioquatix** [comment]
There is a unicode character for small space: U+2009 perhaps it looks better.

**Comment by dominikh** [comment]
That also falls into the category of "you'll have to do that yourself". We'll stick to plain ASCII by default.

**Comment by ioquatix** [comment]
Okay, that's fine, it's just a pity that this library isn't very flexible or easy to use and it hasn't even hit 1.0 yet. Thanks.
