### ISSUE TITLE
Parsing of Bytes as SI Type

### ISSUE THREAD

**Issue by CatCookie** [dominikh/filesize#13]
I din't manage to parse only bytes and pretty print them as SI Type.
There should be an option to specify as which type the string should be parsed or outputted.

e.g.: 
`Filesize.from('12345 B').pretty` always outputs as KiB -> i see no way to output SI types
`Filesize.from('12345 KB').pretty` outputs as MB and not MiB -> everything works fine

Your regex cant diffentiate between SI and binary if you only provide Bytes.

**Comment by CatCookie** [comment]
Found an alternative:
`Filesize.new(123123, type=Filesize::SI).pretty`

**Comment by dominikh** [comment]
The alternative you have found is the canonical solution to this. Or, the more general solution, would be

```
f = Filesize.from(s)
f = Filesize.new(f.to_i, Filesize::SI)
```

if you have to accept user input.

**Comment by CatCookie** [comment]
Maybe you should add this to your ussage documentation. 
I hab to "crawl" through your code for it.

**Comment by Mikeks81** [comment]
Agreed that this should be in the documentation. I was going through the code to try and do the same.
